version: '3.7'

services:
  backend:
    build:
      context: ./be/Go
      dockerfile: Dockerfile
    volumes:
      - ./be/Go:/app
    ports:
      - "8000:8000"
    command: go run main.go  # replace with your actual command

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    volumes:
      - ./fe:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start  # replace with your actual command